-- Inserção de 44 produtos eletrônicos na tabela 'product'
INSERT INTO product (name, brand_id, author_id, price, description, created_at, updated_at) VALUES
('Smartphone Galaxy S22', 1, 1, 799.99, 'Smartphone com câmera avançada.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('iPhone 14', 2, 2, 999.99, 'Novo iPhone com funcionalidades avançadas.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smart TV Sony Bravia', 3, 3, 1199.99, 'Smart TV com resolução 4K e qualidade de som superior.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Notebook LG Gram', 4, 1, 1499.99, 'Notebook ultraleve com bateria de longa duração.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smartphone Xiaomi 13', 5, 2, 699.99, 'Smartphone com ótimo custo-benefício.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Monitor Dell UltraSharp', 6, 3, 399.99, 'Monitor de alta resolução para uso profissional.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Impressora HP LaserJet', 7, 1, 249.99, 'Impressora laser com impressão rápida.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Notebook Lenovo ThinkPad', 8, 2, 1199.99, 'Notebook empresarial com alta performance.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smartphone Asus ROG Phone 5', 9, 3, 1099.99, 'Smartphone gamer com alto desempenho.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chromebook Acer Spin', 10, 1, 349.99, 'Chromebook conversível com tela sensível ao toque.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fone de Ouvido Philips SHP9600', 11, 2, 129.99, 'Fone de ouvido com áudio de alta qualidade.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Câmera Panasonic Lumix', 12, 3, 899.99, 'Câmera digital compacta com lente de alta qualidade.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Televisor Toshiba Fire TV', 13, 1, 549.99, 'Smart TV com integração Alexa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Consola Microsoft Xbox Series X', 14, 2, 499.99, 'Console de última geração.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Processador Intel Core i9', 15, 3, 549.99, 'Processador de alta performance.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Placa de Vídeo Nvidia RTX 3080', 19, 1, 799.99, 'Placa gráfica para jogos e edição de vídeo.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Teclado Corsair K95', 20, 2, 199.99, 'Teclado mecânico RGB.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mouse Logitech G502', 18, 3, 79.99, 'Mouse gamer de alta precisão.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smartwatch Samsung Galaxy Watch 5', 1, 1, 349.99, 'Relógio inteligente com monitoramento de saúde.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tablet Apple iPad Air', 2, 2, 599.99, 'Tablet com tela Retina e processador M1.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Notebook Dell XPS 15', 6, 3, 1899.99, 'Notebook premium com tela InfinityEdge.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Impressora Multifuncional Epson EcoTank', 7, 1, 299.99, 'Impressora com tanque de tinta econômica.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fone de Ouvido Sony WH-1000XM4', 3, 3, 349.99, 'Fone de ouvido com cancelamento de ruído.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smartphone OnePlus 10 Pro', 5, 2, 799.99, 'Smartphone com carregamento rápido.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Desktop HP Pavilion Gaming', 7, 1, 1099.99, 'PC gamer com alta performance.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Notebook Asus ZenBook', 9, 3, 1399.99, 'Notebook ultrafino com tela OLED.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Televisor LG OLED C1', 4, 1, 1299.99, 'Smart TV com tecnologia OLED.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Processador AMD Ryzen 7', 16, 2, 399.99, 'Processador para desktops.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smartphone Sony Xperia 5', 3, 3, 699.99, 'Smartphone compacto com câmera de alta qualidade.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smart Speaker Amazon Echo Dot', 14, 2, 49.99, 'Alto-falante inteligente com Alexa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Monitor Samsung Odyssey G7', 1, 1, 699.99, 'Monitor gamer curvo de alta taxa de atualização.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Notebook Acer Aspire 5', 10, 2, 649.99, 'Notebook com excelente custo-benefício.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Câmera Nikon D7500', 13, 3, 1199.99, 'Câmera DSLR com alta sensibilidade ISO.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Roteador TP-Link Archer AX73', 20, 1, 149.99, 'Roteador Wi-Fi 6 de alta velocidade.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tablet Samsung Galaxy Tab S7', 1, 1, 649.99, 'Tablet premium com S Pen.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smartphone Motorola Edge 30', 5, 2, 499.99, 'Smartphone com tela curva OLED.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Placa Mãe Asus TUF Gaming X570', 9, 3, 249.99, 'Placa-mãe para jogos.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Projetor Epson PowerLite', 7, 1, 899.99, 'Projetor com alta resolução.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Câmera GoPro Hero 10', 12, 3, 399.99, 'Câmera de ação compacta.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fone de Ouvido Bose QuietComfort', 3, 3, 299.99, 'Fone de ouvido premium com cancelamento de ruído.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Console Nintendo Switch OLED', 14, 2, 349.99, 'Console híbrido com tela OLED.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('HD Externo Seagate 5TB', 18, 3, 149.99, 'Armazenamento portátil de alta capacidade.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mouse Razer DeathAdder', 18, 3, 49.99, 'Mouse ergonômico para jogos.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Teclado Gamer HyperX Alloy', 20, 2, 99.99, 'Teclado mecânico com iluminação.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Placa de Captura Elgato HD60', 19, 1, 179.99, 'Placa de captura para streamers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
